language: python
sudo: enabled
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
dist: bionic
install:
  - sudo apt-get install coinor-cbc coinor-libcbc-dev -y
  - pip install -r requirements.txt
script:
  - export PYTHONPATH=$(pwd):$PYTHONPATH
  - coverage run --rcfile=./.coveragerc setup.py test
  - coverage report --rcfile=./.coveragerc -i
after_success:
  - coveralls